server:
  port: 2222
  
spring:
  application:
    name: user-service
    
feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8888}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
